[general]
import = [
    "~/.config/alacritty/themes/hyper.toml"
]

[cursor]
style.blinking = "Never"

[window]
option_as_alt = "OnlyLeft"
#opacity = 0.9

[colors.primary]
background = '#000000'

[font]
size = 15.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "Slash", mods = "Control", chars = "\u001f" }
]
